# Remove all auxiliary files created during document compilation.
clean:
	find . -name "*.pdf" -delete
	find . -name "*.aux" -delete
	find . -name "*.idx" -delete
	find . -name "*.log" -delete
	find . -name "*.out" -delete
